### PR TITLE
Update files config.guess and config.sub

### PR DESCRIPTION
**Pull request by benz0li**
- Enable build on Linux aarch64

Resolve kasperdanielhansen/Rgraphviz#11.

### CODE REVIEW

**Comment by benz0li** [comment]
@kasperdanielhansen Please merge and publish a new version.

Thank you.

**Comment by benz0li** [comment]
@kasperdanielhansen Please merge and publish a new version on Bioconductor.

Thank you.

**Comment by kasperdanielhansen** [comment]
Will be part of 2.41.2 which will be committed today.

**Comment by benz0li** [comment]
Thank you @kasperdanielhansen

**Pull request merged**
